# Generated by Django 5.0.4 on 2024-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
    ]
