# Generated by Django 5.0.4 on 2024-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_info',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
