# Generated by Django 5.0.4 on 2024-04-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_customuser_best_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='best_user',
        ),
    ]
