# Generated by Django 5.0.4 on 2024-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0014_customuser_follow_usertodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='img',
            field=models.ImageField(blank=True, upload_to='to_do_img/'),
        ),
    ]
