# Generated by Django 5.0.4 on 2024-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0018_alter_message_author_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='image_message/'),
        ),
    ]
